target-version = "py38"

exclude = [
    ".git",
    "build",
    "dist",
    "maybe",
]


[format]
docstring-code-format = true

[lint]
extend-select = [
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "CPY",  # flake8-copyright
  "D",    # pydocstyle
  "E",    # pycodestyle
  "N",    # pep8-naming
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]

[lint.flake8-copyright]
min-file-size = 1
notice-rgx = "Copyright © 20\\d{2}(-20\\d{2})? {2}"

[lint.mccabe]
max-complexity = 6

[lint.pydocstyle]
convention = "google"
