name: Scan with zizmor

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      zizmor: ${{ steps.filter.outputs.zizmor }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check for file changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            zizmor:
              - .github/workflows/*.yml

  zizmor:
    needs: changes
    if: needs.changes.outputs.zizmor == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
          annotations: true
