name: Scan with zizmor

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      zizmor: ${{ steps.filter.outputs.zizmor }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check for file changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            zizmor:
              - .github/workflows/*.yml

  zizmor:
    needs: changes
    if: needs.changes.outputs.zizmor == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
          annotations: true
