name: Scan with zizmor

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      zizmor: ${{ steps.filter.outputs.zizmor }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check for file changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            zizmor:
              - .github/workflows/*.yml

  zizmor:
    needs: changes
    if: needs.changes.outputs.zizmor == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        with:
          advanced-security: false
          annotations: true
